---
title: "Salmonella enterica Typing Report" 
date: "`r Sys.Date()`"
output: html_document
params:
  lims: ""
  csv : ""
---

```{css, echo = FALSE}
  .nav-pills>li>a:hover, .nav-pills>li>a:focus, .nav-pills>li.active>a,     .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus{
     background-color: darkblue;
     }
```

<br>


### Serotype
```{r, results='asis',echo=FALSE}
  
  sero_raw <- read.csv(params$lims,header = TRUE,sep = ",")
  sero_final <- sero_raw[,c(7,8,9,10,12,13,14,16)]
  print(knitr::kable(sero_final,caption = "Serovar - \n Predicted using Salmonella In Silico Typing Resource (SISTR) commandline tool. For more info please see https://github.com/phac-nml/sistr_cmd"))
  cat("\n")
  
  samplelist <- read.csv(params$csv,header=FALSE,sep = ',')[-1,]
  sampleid <- samplelist[,c(1)]
```
<br>

### BUSCO RESULTS {.tabset .tabset-pills}
```{r, results='asis',echo=FALSE}
  for (i in sampleid){
    cat("####", i, "\n")
    busco_id <- (paste(i,"_busco.txt",sep=""))
    busco_file <- readLines(busco_id)
    # Display the content
    cat("```\n")
    cat(busco_file, sep = "\n")
    cat("\n```\n")
    }


```
<br>